name: 'Firebase App Distribution Upload'
description: 'Uploads an artifact to Firebase App Distribution'
author: 'Samuel Abada <@mastersam07>'
branding:
  color: 'orange'
  icon: 'upload-cloud'
inputs:
  serviceCredentialsFileContent:
    description: 'Service account key JSON content for Firebase authentication'
    required: true
  appId:
    description: 'The app ID of your Firebase app'
    required: true
  file:
    description: 'Path to the artifact file to upload'
    required: true
  groups:
    description: 'Distribution groups to distribute the artifact to'
    required: false    
  releaseNotes:
    description: 'Release notes for the uploaded artifact'
    required: false
runs:
  using: node20
  main: 'dist/index.js'
